apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  namespace: {{ .Values.metadata.namespace }}
  labels:
    io.agent.service: controlplane-agent-{{ .Values.metadata.gwType }}
  name: controlplane-agent-{{ .Values.metadata.gwType }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.agent.service: controlplane-agent-{{ .Values.metadata.gwType }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.agent.service: controlplane-agent-{{ .Values.metadata.gwType }}
    spec:
      containers:
        - env:
            - name: backendUrl
              value: {{ .Values.env.backendUrl }}
            - name: gateway-config
              value: /workspace/{{ .Values.metadata.gwType }}Config.yaml
          image: {{ .Values.env.image }}
          name: controlplane-agent-{{ .Values.metadata.gwType }}
          resources: {}
          volumeMounts:
            - mountPath: /workspace
              name: {{ .Values.metadata.gwType }}configvol
      restartPolicy: Always
      volumes:
        - name: {{ .Values.metadata.gwType }}configvol
          secret:
            secretName: {{ .Values.metadata.gwType }}config
