apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.gwType }}config
  namespace: {{ .Values.metadata.namespace }}
data:
  {{ .Values.metadata.gwType }}Config.yaml: {{ .Values.data.configFile }}
